In [1]:
import pandas as pd

## Formatting Hindu Catalogue

In [2]:
hin_directory = 'data\Minority ARC data\Hindu\catalogue final.csv'
hin_data = pd.read_csv(hin_directory)

In [3]:
# Select columns "Theme", "Comment" and "ExpertExplanation"
hin_data = hin_data[["Theme", "Comment", "ExpertsExplanation"]]

In [4]:
# Select rows where "ExpertsExplanation" is not NaN
hin_withExplanations = hin_data.dropna(subset=["ExpertsExplanation"])

In [5]:
# Comment with explanations
hin_withExplanations

,Theme,Comment,ExpertsExplanation
8,NaN,আলহামদুলিল্লাহ প্রায় ৩০০ বছরের পূর্ব থেকে সংগঠ...,মাদারীপুরের কালকিনিতে বন্ধ করে দেওয়া হলো শত বছ...
11,বুয়েটে দীপাবলিতে শ্রী রাম লেখা,"বুয়েটে দীপাবলি উপলক্ষে প্রদীপ দিয়ে ""জয় শ্রী রা...",দীপাবলি উদযাপন মূলত সনাতনীদের আরাধ্য ভগবান শ্...
12,শিব লিঙ্গ পূজা কুরুচিপূর্ণ,"শিব ৬০,০০০ বিবাহ করেছিল। সে মারা যাবার পর তার ...",এই দাবিটা কোথা থেকে পেয়েছে তার কোনো সূত্র নে...
13,শিব গণেশ ভুল বৈশিষ্ট্য,"শিব তার নিজের ছেলে গনেশকে চিনতে পারেনি, গর্দান...","একজন পিতা তার সন্তানকে চিনবে না, এরকম ধারণা কর..."
14,দেবদাসী পতিতা অশ্লীলকর্ম,দেবদাসীর ও যোগিনীর মত পতিতা চরিত্রের সাথে ভগবা...,এই তথ্যটিরও কোনো রেফারেন্স নেই। যোগিনী অথচ পতি...
15,অশ্লীল ভঙ্গিমা রক্ত দূর্গা কালী,"অশ্লীল ভঙ্গিমায় উলঙ্গ নারী, মুখে ও দাঁতে রক্ত...",সনাতন শাস্ত্রে দূর্গা শব্দটিকে বিশ্লেষন করা হয়...
16,কৃষ্ণ মামী অবৈধ,কৃষ্ণা যদি সৃষ্টিকর্তা হয় তবে সে কেন তার মামী...,কৃষ্ণা কে? কৃষ্ণকে কৃষ্ণা বানিয়ে দিয়েছে। যাইহো...
17,রাম কিভাবে সৃষ্টিকর্তা হতে পারে হনুমান ক্ষমতা,কিভাবে রাম সৃষ্টিকর্তা হতে পারে কারণ সে প্রয়ো...,"পুরাণ অনুসারে, শ্রীরাম হচ্ছে ঈশ্বরের ৭ম অবতার।..."
18,রাম হনুমান দুই ভাই সৃষ্টিকর্তা অপরাধ,রাম হনুমানের দুই ভাইকে কেন অকারনে খুন করলেন যে...,রাম হনুমানের ভাইকে হত্যা করেননি। হত্যা করেছেন ...
19,রাম রাবণ শয়তান ক্ষমতা,রাবন যদি শয়তান হয়ে একদিনে লঙ্কায় পৌঁছাতে পা...,শ্রীরাম সমুদ্র পার হয়েছেন সমগ্র বানর সেনা নিয়ে...
20,হুদুর দুর্গা আর্য গণিকা,দাঁশায় উৎসব বা দাসাই উটসব হলো খেরোয়াল সাঁওতা...,(১) সাঁওতালদের নিয়ে যতগুলো ক্ষেত্রসমীক্ষা হয়েছ...
21,হিন্দু সরকারি চাকরি শতকরা,বাংলাদেশে হিন্দু ৭% কিন্তু সরকারি চাকুরীতে এদে...,বাংলাদেশের সরকারী চাকুরীর ক্ষেত্রে সংখ্যালঘুদে...
22,NaN,এই ভন্ডামি জন্মের থেকেই দেখে আসতাছি কিছু ভালো ...,ঈশ্+বর= ঈশ্বর। অর্থাৎ যিনি মঙ্গলময় ও সমস্ত মঙ্...
29,মুর্তি ভাঙ্গা,"""কিছু মানবতার ফেলিওয়ালাদের দেখতেছি, মূর্তি পা...","🔳 জগতে নিরাকারবাদী বহু সম্প্রদায় আছে, যাহারা অ..."
30,হিন্দু ধর্মাবলম্বীদের মূর্তিপূজা করা উচিত নয়,হিন্দু ধর্মাবলম্বীদের মূর্তিপূজা করা উচিত নয় ক...,"""ন তস্য প্রতিমা অস্তি যস্য নাম মহদ্ যশঃ।হিরন্য..."
31,হিন্দু ধর্মাবলম্বীদের মূর্তিপূজা করা উচিত নয়,হিন্দু ধর্মাবলম্বীদের মূর্তিপূজা করা উচিত নয় ক...,গীতা ৭/২০-২২ শ্লোক তিনটা পড়লে উত্তরটা পরিস্কার...
32,হিন্দু ধর্মাবলম্বীদের মূর্তিপূজা করা উচিত নয়,হিন্দু ধর্মাবলম্বীদের মূর্তিপূজা করা উচিত নয় ক...,◾ বানোয়াট তথ্যঃ\nব্রহ্ম সুত্র বেদের নয়। ব্রহ...
33,হিন্দু ধর্মাবলম্বীদের মূর্তিপূজা করা উচিত নয়,হিন্দু ধর্মাবলম্বীদের মূর্তিপূজা করা উচিত নয় ক...,সম্ভুতি ও অসম্ভুতির তাৎপর্য না বুঝেই মূর্খের দ...
34,অশ্লীল কর্ম,"রিগবেদ অধ্যায়-৩, খন্ড-৩১, শ্লোক: ১-২ ‘‘পিতা ত...",তাদের এই দাবিটা পড়েই এদের দৌড় সম্পর্কেভালো ধা...
35,শিব মাদক,শিব কেন মাদক সেবন করেন?,"যারা গাঁজাসহ অন্যান্য মাদক সেবন বা নেশা করে, ত..."
36,শিব লিঙ্গ,শিব লিঙ্গ নিয়ে হিন্দু মেয়েরা কি করে? তারা বা...,এই প্রশ্নটি অশ্লীল উদ্দেশ্য নিয়ে করা হয়েছে। শি...
37,NaN,একজন শিষ্টাচার হিন্দু কোন যুক্তিকতায় তার স্ত্...,প্রথমত এই প্রশ্নটা খুবই অপমানজনক। হয়তো প্রশ্ন...
38,NaN,"শিব, কৃষ্ণ, রাম এরা সবাই ভগবান বা সৃষ্টিকর্তা।...",এরকম নির্বোধের মতো প্রশ্ন দেখলে প্রশ্নকর্তার ম...
39,NaN,মর্যাদা পুরুষোত্তম শ্রীরামচন্দ্র এবং মাতা সীতা...,এই সমস্যাটির মূল উৎপত্তি হলো বাল্মীকি রামায়ণের...
40,NaN,শ্রীরাম কেন শূদ্র শম্বুককে হ.ত্যা করেছিলেন বেদ...,রামকে বলা হয় মর্যাদা পুরুষোত্তম।\n\n\nমর্যাদাপ...
41,NaN,"রামের প্রাণ যদি আমাকে প্রতিষ্ঠা করতে হয়, রাম ...",প্রাণ প্রতষ্ঠা কথার অর্থ হলো সর্বব্যাপী পরমব্র...
42,NaN,"রাম, লক্ষ্মণ, সীতা এরা সবাই সু/ইসাইড করেছিল কে...","শুধু এঁরা নয়, কৃষ্ণ, বলরাম, ভীষ্ম, দধিচী মুনি ..."
43,NaN,কৃষ্ণ কি পাপী ছিল? যে কারণে অভিশপ্ত হয়ে ব্যাধে...,এ সম্পর্কে রাজ শেখর বসুর অনুবাদ করা মহাভারতে ব...
44,NaN,দুর্গা পূজা করতে পতিতালয়ের মাটি কেন লাগে?,উত্তর ১ঃ দুর্গোৎসবে বা দেবপ্রতিষ্ঠার সময় বেশ্...
45,NaN,"সনাতন ধর্ম মতে, দেবতার সংজ্ঞা কী? পবিত্র ভগবদ্...","সনাতন ধর্ম মতে, দেবতার সংজ্ঞা কী? পবিত্র ভগবদ্..."
46,NaN,বেদে বলা হইছে যে সৃষ্টিকর্তার কোনো প্রতিমা হয়...,"""ন তস্য প্রতিমা অস্তি""\n\nএর অর্থ এটা নয় যে মূ..."
47,NaN,"হিন্দুরা কেন গোবর, গোমূত্র পান করে?",প্রথমত প্রশ্নটি খুবই অদ্ভুত! গোবর ও গোমূত্র পূ...
48,NaN,কেন কালী তার স্বামীকে হত্যা করে?,দেবী কালী কখনো তাঁর স্বামীকে হত্যা করেনি। শিব ...
49,NaN,মা কালী জিহ্বা বের করে রাখেন কেন এবং এর কারণ কী ?,"মা কালীর সাদা দাঁত সত্ত্বগুনের প্রতীক,লাল জিহ্..."

In [6]:
# Select rows from data where "Comment" is present but "ExpertsExplanation" is not
hin_withoutExplanations = hin_data[hin_data["ExpertsExplanation"].isnull() & hin_data["Comment"].notnull()]

In [7]:
# Drop values in `Comment` that contain text "mp4"
hin_withoutExplanations = hin_withoutExplanations[~hin_withoutExplanations["Comment"].str.contains("mp4")]

In [8]:
# Comment without explanations
hin_withoutExplanations

   Theme                                            Comment ExpertsExplanation
23   NaN                     কৃষ্ণ করলে লীলা আমরা করলে বিলা                NaN
24   NaN            রামঠাপ কি? ঠাপের সাথে রামের কি সম্পর্ক?                NaN
25   NaN  হরে "কৃষ্ণ" হরে "রাম" শেখ হাসিনার বাপের নাম ? ...                NaN
26   NaN                 "হিন্দু কীভাবে শহীদ হয়?" ছবি১ ছবি২                NaN
27   NaN  সংখ্যালঘু সম্প্রদায়ের ধর্মীয় উৎসব সম্পর্কিত পো...                NaN
28   NaN  মূর্তিপূজা করা ঠিক নয়, কারণ "যে ব্যক্তি আল্লাহ...                NaN
50   NaN  হিন্দু ধর্মাবলম্বীদের গ্রন্থে গরুর মাংস খাওয়ার...                NaN
51   NaN  গাভী হিন্দুদের অতি প্রিয় পূজনীয় প্রাণী। গাভী দ...                NaN

In [9]:
# Tag the "Minority" in both dataframes as Hindu

hin_withExplanations.insert(0, "Minority", "Hindu")
hin_withoutExplanations.insert(0, "Minority", "Hindu")

In [10]:
directory = 'data\Minority ARC data\Hindu\catalogue final.csv'
data = pd.read_csv(directory)

## Formatting Chakma Catalogue

In [11]:
chak_directory = 'data\Minority ARC data\Chakma\catalogue Final.csv'
chak_data = pd.read_csv(chak_directory)

In [12]:
# Remove empty rows and replace newline characters
chak_data = chak_data.dropna(subset=["Comment", "ExpertsExplanation"]).replace(r'\n', ' ', regex=True).reset_index(drop=True)

In [13]:
# Add a new column named "Minority" and set it to "Chakma"
chak_data.insert(0, "Minority", "Chakma")

In [14]:
chak_data

,Minority,Theme,Comment,ExpertsExplanation
0,Chakma,NaN,"In 2022, I experienced an uncomfortable incide...",It's important to approach all people with kin...
1,Chakma,NaN,We are secretly maping to make a new separated...,This statement reflects a situation where misi...
2,Chakma,NaN,People often have misconceptions about us and ...,This statement highlights the challenges faced...
3,Chakma,NaN,"বাঙ্গালীদের একটা বড় কাজ হচ্ছে গুজব ছড়ানো,এবং ত...",এই বক্তব্যে মূলত দুটি আলাদা সামাজিক সমস্যার দি...
4,Chakma,NaN,"“হাড্ডি কখনো গোস্ত হয়না, উপজাতি কখনো দোস্ত হয...",This statement sheds light on the deep-seated...
5,Chakma,NaN,I’m currently pursuing undergraduate degree at...,The experience highlights the persistent stere...
6,Chakma,NaN,Due to oppresive circumstances in cht hill tra...,The comment reflects the challenges faced by i...
7,Chakma,NaN,There are many people in our society who degra...,This comment underscores the persistent discri...
8,Chakma,NaN,1.In our hill tribes the main ingredient we us...,The food habits of the hill tribes are deeply...
9,Chakma,NaN,when we go outside the Chittagong hill tracts ...,When individuals from the Chittagong Hill Trac...
10,Chakma,NaN,i think what written in buddhism is killing an...,Your understanding aligns with a core princip...
11,Chakma,NaN,its basically a contradictory content,"The phrase ""it's basically a contradictory con..."
12,Chakma,NaN,"Back in 2018, during our university admission ...",This account reflects the subtle but impactfu...
13,Chakma,NaN,"""একহাতে তালি বাজে না | চাকমাবাসী রা সব সময় উগ...",The passage begins with a well-known Bengali ...
14,Chakma,NaN,"""Shourajit Changma mama tui j bolos chakmara e...","In this passage, the speaker is questioning t..."
15,Chakma,NaN,"Humiliate tribe female - ""Free sexual relation...",It's important to approach sensitive topics l...
16,Chakma,NaN,"""পাহারীদের মেরে ফেলা উচিত, যারা বাংলাদেশী তারা...",এ ধরনের মন্তব্য অত্যন্ত ঘৃণ্য এবং অমানবিক। এট...
17,Chakma,NaN,"""পাহাড়ে সেনাবাহিনী কেন থাকবে? সেই যদি হয় সমত...",উক্তিটি পাহাড়ি অঞ্চলে সেনাবাহিনীর স্থায়ী উপস্থ...
18,Chakma,NaN,"""জনৈক: পাহাড় বাঁচাও, দেশ বাঁচাও!! উপজাতি: সহম...",এই সংলাপটি পাহাড়ি অঞ্চলে স্থানীয় জনগোষ্ঠীর অবস...
19,Chakma,NaN,"""পরিকল্পিতভাবে খাগড়াছড়ি টেকনিক্যাল কলেজের শ...",এই বিবৃতিটি একটি নির্দিষ্ট ঘটনাকে কেন্দ্র করে ...
20,Chakma,NaN,"""তুমি পাহাড়ি, তুমি বাংলাদেশের ৬৪ জেলায় যেকোন...",এই বক্তব্যটি পার্বত্য চট্টগ্রামের নিরাপত্তা ও ...
21,Chakma,NaN,"""ঢাকা শহরে চাকমা পাইলে পাঠানো হবে ঢাকা শহর...","এই বক্তব্যটি অত্যন্ত বিদ্বেষপূর্ণ, উস্কানিমূলক..."
22,Chakma,NaN,"""I still remember Holey Artisan attack. glad ...",The statement appears to reference the Holey A...
23,Chakma,NaN,"""প্রত্যেকটা পাহাড়ি মেয়ের গর্ভে একটা করে বাঙা...",The statement reflects a highly inflammatory a...
24,Chakma,NaN,"""ইউপিডিএফ চাচ্ছে সাধারণ চাকমারা যেন ছাত্রদের ...",The statement seems to be referencing the ongo...
25,Chakma,NaN,"""যারা পাহাড় থেকে সেনা হটানোর দাবি জানাচ্ছেন, ...","The statement ""যারা পাহাড় থেকে সেনা হটানোর দা..."
26,Chakma,NaN,"""উপজাতি ""রা তোমরা যত দিন না বাঙালি বলে পরিচয়...",The statement reflects a concerning attitude o...
27,Chakma,NaN,"""চ্যাং চুং দের জনপ্রিয় খাবার |""","The phrase ""চ্যাং চুং দের জনপ্রিয় খাবার"" (loo..."
28,Chakma,NaN,"""সন্ত্রাসী কর্মকান্ড করবেন আর ধরা পড়লে “নিরীহ...",This statement reflects a blend of nationalis...
29,Chakma,NaN,"""পার্বত্য চট্টগ্রামের পাহাড়গুলোর জঙ্গল পরিষ্ক...",The statement reflects a dismissive and explo...
30,Chakma,NaN,"""When I say, ""Ami upojati cdi"" The upojati I ...",The statement appears to highlight a common li...
31,Chakma,NaN,"""আজ থেকে পাহাড়ের স্বাধীনতা ঘোষণা করা হলো তারি...","The statement ""আজ থেকে পাহাড়ের স্বাধীনতা ঘোষ..."
32,Chakma,NaN,"""কোনো জাগায় যদি চাকমা পাও তাহলে পিঠিয়ে মারো...","এই বাক্যটি অত্যন্ত আক্রমণাত্মক, ঘৃণাসূচক এবং স..."
33,Chakma,NaN,"""বলছিনা কয়েক মিনিট ওয়েট করো উপজাতিং ঈদ বৃষ্...",এই বাক্যটি উপহাসমূলক এবং বিদ্রূপাত্মক ভাষায় ল...
34,Chakma,NaN,"""উপজাতিং মামলাং দিয়েছে আমারং নামেং এখনং আমিং...","উক্ত বাক্যটি (অর্থ: ""উপজাতি মামলা দিয়েছে, আম..."
35,Chakma,NaN,"""Never spoke a word during the massacre ekhon ...",This statement reflects frustration over perc...
36,Chakma,NaN,"""কক্সবাজারের চকরিয়ায় যৌথবাহিনীর অভিযান পরিচ...",The statement details a tragic incident involv...
37,Chakma,NaN,"""আন্দোলন সফল, তবে আংশিক ২৪ ঘন্টার যুদ্ধ শেষে...",This statement reflects the partial success o...

In [15]:
# Randomly choose 8 rows from chak_data and remove them from the dataframe and reset index
chak_withoutExplanations = chak_data.sample(8).reset_index(drop=True)
chak_withExplanations = chak_data.drop(chak_withoutExplanations.index).reset_index(drop=True)

In [16]:
chak_withExplanations

,Minority,Theme,Comment,ExpertsExplanation
0,Chakma,NaN,1.In our hill tribes the main ingredient we us...,The food habits of the hill tribes are deeply...
1,Chakma,NaN,when we go outside the Chittagong hill tracts ...,When individuals from the Chittagong Hill Trac...
2,Chakma,NaN,i think what written in buddhism is killing an...,Your understanding aligns with a core princip...
3,Chakma,NaN,its basically a contradictory content,"The phrase ""it's basically a contradictory con..."
4,Chakma,NaN,"Back in 2018, during our university admission ...",This account reflects the subtle but impactfu...
5,Chakma,NaN,"""একহাতে তালি বাজে না | চাকমাবাসী রা সব সময় উগ...",The passage begins with a well-known Bengali ...
6,Chakma,NaN,"""Shourajit Changma mama tui j bolos chakmara e...","In this passage, the speaker is questioning t..."
7,Chakma,NaN,"Humiliate tribe female - ""Free sexual relation...",It's important to approach sensitive topics l...
8,Chakma,NaN,"""পাহারীদের মেরে ফেলা উচিত, যারা বাংলাদেশী তারা...",এ ধরনের মন্তব্য অত্যন্ত ঘৃণ্য এবং অমানবিক। এট...
9,Chakma,NaN,"""পাহাড়ে সেনাবাহিনী কেন থাকবে? সেই যদি হয় সমত...",উক্তিটি পাহাড়ি অঞ্চলে সেনাবাহিনীর স্থায়ী উপস্থ...
10,Chakma,NaN,"""জনৈক: পাহাড় বাঁচাও, দেশ বাঁচাও!! উপজাতি: সহম...",এই সংলাপটি পাহাড়ি অঞ্চলে স্থানীয় জনগোষ্ঠীর অবস...
11,Chakma,NaN,"""পরিকল্পিতভাবে খাগড়াছড়ি টেকনিক্যাল কলেজের শ...",এই বিবৃতিটি একটি নির্দিষ্ট ঘটনাকে কেন্দ্র করে ...
12,Chakma,NaN,"""তুমি পাহাড়ি, তুমি বাংলাদেশের ৬৪ জেলায় যেকোন...",এই বক্তব্যটি পার্বত্য চট্টগ্রামের নিরাপত্তা ও ...
13,Chakma,NaN,"""ঢাকা শহরে চাকমা পাইলে পাঠানো হবে ঢাকা শহর...","এই বক্তব্যটি অত্যন্ত বিদ্বেষপূর্ণ, উস্কানিমূলক..."
14,Chakma,NaN,"""I still remember Holey Artisan attack. glad ...",The statement appears to reference the Holey A...
15,Chakma,NaN,"""প্রত্যেকটা পাহাড়ি মেয়ের গর্ভে একটা করে বাঙা...",The statement reflects a highly inflammatory a...
16,Chakma,NaN,"""ইউপিডিএফ চাচ্ছে সাধারণ চাকমারা যেন ছাত্রদের ...",The statement seems to be referencing the ongo...
17,Chakma,NaN,"""যারা পাহাড় থেকে সেনা হটানোর দাবি জানাচ্ছেন, ...","The statement ""যারা পাহাড় থেকে সেনা হটানোর দা..."
18,Chakma,NaN,"""উপজাতি ""রা তোমরা যত দিন না বাঙালি বলে পরিচয়...",The statement reflects a concerning attitude o...
19,Chakma,NaN,"""চ্যাং চুং দের জনপ্রিয় খাবার |""","The phrase ""চ্যাং চুং দের জনপ্রিয় খাবার"" (loo..."
20,Chakma,NaN,"""সন্ত্রাসী কর্মকান্ড করবেন আর ধরা পড়লে “নিরীহ...",This statement reflects a blend of nationalis...
21,Chakma,NaN,"""পার্বত্য চট্টগ্রামের পাহাড়গুলোর জঙ্গল পরিষ্ক...",The statement reflects a dismissive and explo...
22,Chakma,NaN,"""When I say, ""Ami upojati cdi"" The upojati I ...",The statement appears to highlight a common li...
23,Chakma,NaN,"""আজ থেকে পাহাড়ের স্বাধীনতা ঘোষণা করা হলো তারি...","The statement ""আজ থেকে পাহাড়ের স্বাধীনতা ঘোষ..."
24,Chakma,NaN,"""কোনো জাগায় যদি চাকমা পাও তাহলে পিঠিয়ে মারো...","এই বাক্যটি অত্যন্ত আক্রমণাত্মক, ঘৃণাসূচক এবং স..."
25,Chakma,NaN,"""বলছিনা কয়েক মিনিট ওয়েট করো উপজাতিং ঈদ বৃষ্...",এই বাক্যটি উপহাসমূলক এবং বিদ্রূপাত্মক ভাষায় ল...
26,Chakma,NaN,"""উপজাতিং মামলাং দিয়েছে আমারং নামেং এখনং আমিং...","উক্ত বাক্যটি (অর্থ: ""উপজাতি মামলা দিয়েছে, আম..."
27,Chakma,NaN,"""Never spoke a word during the massacre ekhon ...",This statement reflects frustration over perc...
28,Chakma,NaN,"""কক্সবাজারের চকরিয়ায় যৌথবাহিনীর অভিযান পরিচ...",The statement details a tragic incident involv...
29,Chakma,NaN,"""আন্দোলন সফল, তবে আংশিক ২৪ ঘন্টার যুদ্ধ শেষে...",This statement reflects the partial success o...

In [17]:
chak_withoutExplanations

,Minority,Theme,Comment,ExpertsExplanation
0,Chakma,NaN,"""উপজাতি ""রা তোমরা যত দিন না বাঙালি বলে পরিচয়...",The statement reflects a concerning attitude o...
1,Chakma,NaN,"""আজ থেকে পাহাড়ের স্বাধীনতা ঘোষণা করা হলো তারি...","The statement ""আজ থেকে পাহাড়ের স্বাধীনতা ঘোষ..."
2,Chakma,NaN,I’m currently pursuing undergraduate degree at...,The experience highlights the persistent stere...
3,Chakma,NaN,"বাঙ্গালীদের একটা বড় কাজ হচ্ছে গুজব ছড়ানো,এবং ত...",এই বক্তব্যে মূলত দুটি আলাদা সামাজিক সমস্যার দি...
4,Chakma,NaN,1.In our hill tribes the main ingredient we us...,The food habits of the hill tribes are deeply...
5,Chakma,NaN,"""বলছিনা কয়েক মিনিট ওয়েট করো উপজাতিং ঈদ বৃষ্...",এই বাক্যটি উপহাসমূলক এবং বিদ্রূপাত্মক ভাষায় ল...
6,Chakma,NaN,"""কক্সবাজারের চকরিয়ায় যৌথবাহিনীর অভিযান পরিচ...",The statement details a tragic incident involv...
7,Chakma,NaN,"""সন্ত্রাসী কর্মকান্ড করবেন আর ধরা পড়লে “নিরীহ...",This statement reflects a blend of nationalis...

In [18]:
# Combine chak_withoutExplanations with hin_withoutExplanations
total_withoutExplanations = pd.concat([chak_withoutExplanations, hin_withoutExplanations]).reset_index(drop=True)

In [19]:
# The goal of total_withoutExplanations is to have a test set of 8 rows of Chakma and 8 rows of Hindu of unseen data
total_withoutExplanations = total_withoutExplanations[["Minority", "Comment"]]

In [20]:
total_withoutExplanations

   Minority                                            Comment
0    Chakma  "উপজাতি "রা তোমরা যত দিন না বাঙালি বলে  পরিচয়...
1    Chakma  "আজ থেকে পাহাড়ের স্বাধীনতা ঘোষণা করা হলো তারি...
2    Chakma  I’m currently pursuing undergraduate degree at...
3    Chakma  বাঙ্গালীদের একটা বড় কাজ হচ্ছে গুজব ছড়ানো,এবং ত...
4    Chakma  1.In our hill tribes the main ingredient we us...
5    Chakma  "বলছিনা কয়েক মিনিট ওয়েট করো  উপজাতিং ঈদ বৃষ্...
6    Chakma  "কক্সবাজারের চকরিয়ায় যৌথবাহিনীর অভিযান  পরিচ...
7    Chakma  "সন্ত্রাসী কর্মকান্ড করবেন আর ধরা পড়লে “নিরীহ...
8     Hindu                     কৃষ্ণ করলে লীলা আমরা করলে বিলা
9     Hindu            রামঠাপ কি? ঠাপের সাথে রামের কি সম্পর্ক?
10    Hindu  হরে "কৃষ্ণ" হরে "রাম" শেখ হাসিনার বাপের নাম ? ...
11    Hindu                 "হিন্দু কীভাবে শহীদ হয়?" ছবি১ ছবি২
12    Hindu  সংখ্যালঘু সম্প্রদায়ের ধর্মীয় উৎসব সম্পর্কিত পো...
13    Hindu  মূর্তিপূজা করা ঠিক নয়, কারণ "যে ব্যক্তি আল্লাহ...
14    Hindu  হিন্দু ধর্মাবলম্বীদের গ্রন্থে গরুর মাংস খাওয়ার...
15    Hindu  গাভী হিন্দুদের অতি প্রিয় পূজনীয় প্রাণী। গাভী দ...

In [21]:
total_withExplanations = pd.concat([chak_withExplanations, hin_withExplanations]).reset_index(drop=True)

In [22]:
total_withExplanations

,Minority,Theme,Comment,ExpertsExplanation
0,Chakma,NaN,1.In our hill tribes the main ingredient we us...,The food habits of the hill tribes are deeply...
1,Chakma,NaN,when we go outside the Chittagong hill tracts ...,When individuals from the Chittagong Hill Trac...
2,Chakma,NaN,i think what written in buddhism is killing an...,Your understanding aligns with a core princip...
3,Chakma,NaN,its basically a contradictory content,"The phrase ""it's basically a contradictory con..."
4,Chakma,NaN,"Back in 2018, during our university admission ...",This account reflects the subtle but impactfu...
...,...,...,...,...
59,Hindu,NaN,"সনাতন ধর্ম মতে, দেবতার সংজ্ঞা কী? পবিত্র ভগবদ্...","সনাতন ধর্ম মতে, দেবতার সংজ্ঞা কী? পবিত্র ভগবদ্..."
60,Hindu,NaN,বেদে বলা হইছে যে সৃষ্টিকর্তার কোনো প্রতিমা হয়...,"""ন তস্য প্রতিমা অস্তি""\n\nএর অর্থ এটা নয় যে মূ..."
61,Hindu,NaN,"হিন্দুরা কেন গোবর, গোমূত্র পান করে?",প্রথমত প্রশ্নটি খুবই অদ্ভুত! গোবর ও গোমূত্র পূ...
62,Hindu,NaN,কেন কালী তার স্বামীকে হত্যা করে?,দেবী কালী কখনো তাঁর স্বামীকে হত্যা করেনি। শিব ...
63,Hindu,NaN,মা কালী জিহ্বা বের করে রাখেন কেন এবং এর কারণ কী ?,"মা কালীর সাদা দাঁত সত্ত্বগুনের প্রতীক,লাল জিহ্..."

In [ ]:
total_withExplanations[["Minority", "Comment", "ExpertsExplanation"]].to_csv("all_prompts.csv", index=False, encoding='utf-8-sig')

In [ ]:
# # For RAG
# total_withExplanations[["Minority", "Comment", "ExpertsExplanation"]].to_html("MyCSV.html")

In [25]:
# total_withoutExplanations[["Minority", "Comment"]].to_html("test_prompts.html")

In [26]:
# total_withoutExplanations.to_csv("test_prompts.csv", index=False, encoding='utf-8-sig')

In [27]:
# total_withExplanations_sample = total_withExplanations.sample(8).reset_index(drop=True)

In [28]:
# total_withExplanations_sample.to_csv("test_prompts_withExplanations.csv", index=False, encoding='utf-8-sig')

In [29]:
# total_withExplanations.to_csv("test_prompts.csv", index=False, encoding='utf-8-sig')